#! /usr/bin/env bash

. files/conf

pid=

restart() {
	kill "$pid"
}

trap restart SIGUSR1

while :; do
	bin/maskin \
		-m "$MIDI_PORT" \
		current/grammar.txt \
		current/chords.txt &
	pid=$!
	wait "$pid"
	echo
done
