#! /usr/bin/env bash

. files/conf

(
	for ((i=0; i<LINES; i++)); do
		bin/poem current/grammar.txt "$RANDOM"
	done
	for ((i=0; i<EMPTY; i++)); do
		echo
	done
) | tee /dev/stderr \
	| bin/print \
	-v 0x28e9 \
	-p 0x0289 \
	-e 0x01 \
	-i 0x00 \
	-t bulk
